version: '3'

services:
  database:
    container_name: postgres_db
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: back_worker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      TZ: 'Asia/Seoul'
    expose:
      - "5432:5432"
    networks:
      - test_network

  application:
    container_name: back_worker
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/back_worker
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network:
