server:
  port:
    9001

spring:
  application:
    name:
      back-worker
  sql:
    init:
      platform: postgresql
      mode: never # always
      schema-locations:
      - classpath:schema.sql
      data-locations:
      - classpath:data.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/back_worker # 데이터베이스 링크 설정
    username: postgres
    password: root
  zipkin:
    base-url: http://localhost:9412
    
mybatis:
  type-aliases-package: kr.co.dbinc.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka # 서버에 따라 다르게 설정

logging:
  level:
    org:
      springframework:
        web:
          cors: DEBUG
  # 쿠버네티스에서의 공유 폴더 설정으로 elasticsearch 연결하는 방식으로 활용
  #file:
  #  path: /logs
