name: Deploy to AWS EC2 using Docker

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_SSH_USER: ${{ secrets.EC2_SSH_USER }}
  EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

jobs:
  build-and-push-docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # 추후 application.yml 에 대해서는 append 하는 식으로 반영할 것.
    #- name: Set up application.properties
    #  run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties

    - name: Change gradlew permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    # 도커 이미지 빌드
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:latest

    # 도커 허브 로그인
    - name: Login to Docker Hub using Access Token
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # 도커 태그 설정
    - name : Set the tag of Docker image
      run: docker tag ${{ env.DOCKER_IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}

    # 도커 이미지 업로드
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}


  deploy-to-ec2:

    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_SSH_USER }}
        key: ${{ env.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo docker stop ${{ env.DOCKER_IMAGE_NAME }}
          sudo docker rm ${{ env.DOCKER_IMAGE_NAME }}

          sudo docker pull ${{ env.DOCKER_IMAGE_NAME }}
          sudo docker run --name ${{ env.DOCKER_IMAGE_NAME }} -d -p 9001:9001 -e TZ=Asia/Seoul ${{ env.DOCKER_IMAGE_NAME }}
